### PR TITLE
expose ua tags to js throught bridge on ios and android

### PR DESCRIPTION
**Pull request by manuelkch**

### CODE REVIEW

**Comment by manuelkch** [comment]
Could someone have a look at it, or is this repo because out of deprecation reasons not maintained anymore ?

**Comment by evandroeisinger** [comment]
@manuelkch yes, this repository is not anymore maintained, so I advise you to use the official Urban Airship React Native module: https://github.com/urbanairship/react-native-module

**Comment by manuelkch** [comment]
@evandroeisinger thanks for your response. So we will continue using my fork til we get budget for a migration :)

**Comment by rlepinski** [comment]
@manuelkch We wrote a migration guide to go from this module to the new one - https://github.com/urbanairship/react-native-module/blob/master/ReactNativeUAMigration.md

**Pull request closed without merging**
