### PR TITLE
Fix #32 : Add public dispatchNotificationEvent to ios implementation

### LINKED ISSUE #32: Know when the notification permission was accepted
Hi @rlepinski ,

I will create a pull request on this project, that will enable the possibility to know on javascript when the user accepted the notification permission's dialog on iOS and Android 6+.

On iOS there is a **didRegisterForRemoteNotificationsWithDeviceToken** method that you can declare on AppDelegate.m and you will receive there if the user confirmed the notification permission's dialog.

On Android there is a **onRequestPermissionsResult** method of an Activity, that you can declare to know if a user confirmed a permission dialog that you called on a given Activity (https://developer.android.com/training/permissions/requesting.html#perm-check).

The problem is knowing how to get the permission's result on Android 6+, if is the Urban Airship SDK that controls this permission's request.
There is some sort of callback that Urban Airship Android's SDK give, that I can use to know if a user accepted the notification permission's dialog? Or any other way to know that?

Thank you in advance for your time! :D

### PR DESCRIPTION
**Pull request by guilhermebruzzi**
Add public dispatchNotificationEvent to ios implementation and explaining on README how to know on ios when the user accepted the notification.

### CODE REVIEW

**Comment by rlepinski** [comment]
This only works if the app is not set up for background push and could potentially dispatch the accepted event multiple times. Instead you should listen for http://docs.urbanairship.com/reference/libraries/ios/latest/Protocols/UARegistrationDelegate.html#/c:objc(pl)UARegistrationDelegate(im)notificationAuthorizedOptionsDidChange and dispatch a more generic event like "notification_authorization_changed" with the types that user currently has enabled for the app.

**Comment by lucasts** [comment]
Hey @emilianoeloi are you still working on this? Can we close it or follow @rlepinski suggestion

**Comment by ShMcK** [comment]
Any progress on this issue?

**Comment by lucasts** [comment]
@ShMcK  I'm not actively working on this issue.

If you have time, an updated code with @rlepinski suggestions would be nice.

**Pull request closed without merging**
